codota/tabnine-intellij

src/main/java/com/tabnine/TabNineCompletionContributor.java

Protect from string index out of bounds

---

src/main/java/com/tabnine/TabNineCompletionContributor.java

Recursively check delegates in the case the lookup element is a wrapper.
Fixes #5.
In the case of the error reported, it seems that it is caused by the `LookupElement` being wrapped with a `PolicyDecorator` by `CompletionService`.

Fix assertion error when matching a decorator on top of a lookupelement

---

src/main/java/com/tabnine/TabNineCompletionContributor.java

https://codota.zendesk.com/agent/tickets/2410
I couldn't reproduce so I'm not sure what's causing this and how to fix it. Meanwhile we'll just catch runtime exceptions when inserting a completion (so it won't jump to the user) and write more data the the log.

This was reported by a user in the below ticket:

---

src/main/java/com/tabnine/intellij/completions/InlayHoverMouseMotionListener.java
src/main/java/com/tabnine/intellij/completions/LimitExceededLookupElement.java

Bug fix: Don't add the 'limit exceeded' inlay if one is already displayed at the current line.

Use info messages background color for 'limit exceeded' inlay hover.

---

src/main/java/com/tabnine/binary/requests/notifications/BinaryNotification.kt
src/main/java/com/tabnine/binary/requests/notifications/shown/NotificationShownRequest.kt
src/main/java/com/tabnine/binary/requests/statusBar/StatusBarPromotionBinaryResponse.kt
src/main/java/com/tabnine/binary/requests/statusBar/StatusBarPromotionShownRequest.kt
src/main/java/com/tabnine/general/DependencyContainer.java
src/main/java/com/tabnine/lifecycle/BinaryNotificationsLifecycle.kt
src/main/java/com/tabnine/lifecycle/BinaryPromotionStatusBarLifecycle.kt
src/main/java/com/tabnine/selections/TabNineLookupListener.java
src/main/java/com/tabnine/statusBar/StatusBarUpdater.kt

Added missing fields to NotificationShownRequest, BinaryNotification, StatusBarPromotionBinaryResponse and StatusBarPromotionShownRequest.
Update status bar on selection (instead of just waiting for the poller).
Display status bar messages in all open project windows (instead of just the first opened one).

Send the message id in 'Status Bar Promotion Shown' requests.

---

src/main/java/com/tabnine/TabnineFileTypeFactory.java
src/main/java/com/tabnine/TabnineIgnoreFileType.java
src/main/java/com/tabnine/TabnineProjectModelFileType.java
src/main/java/com/tabnine/TabnineRootFileType.java
src/main/resources/META-INF/plugin.xml

Intellij recommend tabnine when:
> The IntelliJ Platform IDEs will recommend a plugin for installation in one of the following cases:
> 
> If a project contains files of types which are unsupported by the running IDE but are supported by a plugin available in the plugin repository.
> 
> If a project was created in n different IDE installation which had the plugin installed, and includes shared settings (modules, facets, artifacts, or run configurations) configured using the plugin.
> 
> 
the instructions are here:
https://plugins.jetbrains.com/docs/marketplace/intellij-plugin-recommendations.html#file-type
(they aren't good)
Tested locally by debugging and witnessing that `.tabnine.model` files have the tabnine icon in the project tree.
> To verify that the file type is registered …

try to recommend tabnine when certain file extensiosn exist

---

src/main/java/com/tabnine/inline/AcceptInlineCompletionAction.java
src/main/java/com/tabnine/inline/CompletionPreview.java
src/main/java/com/tabnine/inline/InlineHints.java
src/main/resources/META-INF/plugin.xml

Fixing the major bug where the inline completion mute by mistake the editor Tab action.
The problem was missing `isEnable` implementation.
Also in this PR:
- Changed the `AcceptInlineCompletionHandler` to be a subclass of `EditorWriteActionHandler` (eliminating the need of `runWriteCommandAction` call when applying the selected inline completion)
- Change the inline text hint to be more friendly (in case no shortcut is set to one of the actions)
- Remove old and irrelevant entries from the `plugin.xml`

Inline tab bug fix

---

src/main/java/com/tabnine/inline/CompletionPreview.java
src/main/java/com/tabnine/inline/InlineCompletionHandler.java
src/main/java/com/tabnine/inline/TabnineDocumentListener.java
src/main/java/com/tabnine/selections/AutoImporter.java
src/test/java/com/tabnine/plugin/InlineCompletionTests.java
src/test/java/com/tabnine/unitTests/InlineStringProcessorTests.kt

1. Debounce document listener for a short amount of time, to tame calls to the listener.
*Why?*
Mainly for snippets - They appear on empty lines, so if you hit a `\n` and the IDE adds indentation (i.e `\n____`) - It will **sometimes** trigger the listener **twice** - for the newline and for the indentation. This causes snippets to appear with the wrong indentation sometimes, and overall a bad behaior. It's also good for auto-filled chars, like brackets - there's no need to trigger for `(` and `)` separately (not at all actually - this is being handled in a separate condition).
*Double debouncing*
There's another debounce inside `InlineCompletionHandler.java` - So why 2 debouncers?
If you'll have only the outer debouncer you wouldn't issue querties to the binary at all if the call is being …

More fixes to inline UX

---

src/main/java/com/tabnine/inline/TabnineDocumentListener.java

`document.getText` throws `IndexOutOfBoundsException` in some cases and its legit - in these cases the text is obviously not auto-filled, so no special action should be taken

handle get text exception

---

src/main/java/com/tabnine/inline/TabnineDocumentListener.java

there was this annoying behavior that when you, for example, `ctrl+v` something into the ide tabnine would hop in and suggest. i disabled it by asserting that the event's new length is exactly 1 - meaning that you typed a single char.

show suggestions only when a single char has been typed

---

src/main/java/com/tabnine/binary/requests/autocomplete/ResultEntry.java
src/main/java/com/tabnine/binary/requests/notifications/shown/SnippetShownRequest.kt
src/main/java/com/tabnine/general/StaticConfig.java
src/main/java/com/tabnine/inline/InlineCompletionHandler.java
src/main/java/com/tabnine/inline/OnCompletionPreviewUpdatedCallback.kt
src/main/java/com/tabnine/intellij/completions/CompletionUtils.java
src/main/java/com/tabnine/prediction/TabNineCompletion.java

The below issue has been solved by using the new api version 4.0.57
---
Current behavior is that if you received a snippet, lets say:
```javascript
function average(arr) {
// 'let sum = 0;...'
```
and you continue typing:
```javascript
function average(arr) {
let // 'sum = 0;...'
```
it'll count as 2 separate `SnippetShown` events.
i think its ok, since (at least in this plugin) currently the snippet disappears and re-appears after some debouncing. 
@dimacodota wdyt?

send snippet shown event

---

src/main/java/com/tabnine/inline/render/GraphicsUtils.kt
src/main/java/com/tabnine/inline/render/experimental/BlockElementRenderer.kt
src/main/java/com/tabnine/inline/render/experimental/InlineElementRenderer.kt
src/main/java/com/tabnine/userSettings/AppSettingsComponent.kt
src/main/java/com/tabnine/userSettings/AppSettingsConfigurable.kt
src/main/java/com/tabnine/userSettings/AppSettingsState.kt
src/main/resources/META-INF/plugin.xml

Added `Tabnine: Settings` section to the settings panel:
Which controls the color of the inline hint. Don't need to restart after changing color, and the chosen color gets persisted to the disk.
Settings implementation is taken from the docs here: https://plugins.jetbrains.com/docs/intellij/settings-tutorial.html

add color picker settings for inline hint

---

src/main/java/com/tabnine/general/StaticConfig.java
src/main/java/com/tabnine/inline/render/GraphicsUtils.kt
src/main/java/com/tabnine/userSettings/AppSettingsComponent.kt
src/main/java/com/tabnine/userSettings/AppSettingsConfigurable.kt
src/main/java/com/tabnine/userSettings/AppSettingsState.kt

- **Use default color:** Overrides user's choice with the default one
- **Log File Path**: equivalent to the `idea.properties` one, and its the preferred one (i.e if both are set, the one from the settings panel is taken)

settings panel: log file path, default color checkbox, disable if inline disabled

---

.github/workflows/compatibility-eap.yml
.github/workflows/compatibility-stable.yml
.github/workflows/compatibility.yml
build.gradle
src/main/java/com/tabnine/Initializer.java
src/main/resources/META-INF/plugin.xml

1. fixed `Initializer` to use an api that's compatible with 2022.1 (eap)
2. compatibility jobs:
2.1 on push: check compatibility against 2019.3 and current stable
2.2 nightly: check compatibility against latest eap

making the plugin compatible with 2019.3 - latest eap

---

src/main/java/com/tabnine/inline/CompletionPreview.java
src/main/java/com/tabnine/inline/CompletionState.java
src/main/java/com/tabnine/inline/InlineCompletionHandler.java
src/main/java/com/tabnine/inline/TabnineDocumentListener.java
src/main/java/com/tabnine/intellij/completions/CompletionUtils.java
src/main/java/com/tabnine/intellij/completions/TabNineCompletionContributor.java
src/main/java/com/tabnine/prediction/TabNineCompletion.java
src/main/java/com/tabnine/selections/CompletionPreviewListener.java
src/main/java/com/tabnine/selections/TabNineLookupListener.java
src/test/java/com/tabnine/plugin/InlineCompletionTests.java

Follow up on https://github.com/codota/tabnine-intellij/pull/278
Instead of the deprecated api `CompletionData.findPrefixStatic`, using `old_prefix` field from the binary (This is also how our vscode plugin handles it).

use old_prefix instead of deprecated api

---

src/main/java/com/tabnine/userSettings/AppSettingsState.kt

the previous name was one taken from a general example somewhere on the internet - so if any other random plugin copied the same example we'll have collisions.
This is a breaking change, i.e user settings will be reset to default.
We only have the log file path & inline color there, so i dont think its too much trouble, but worth mentioning.

change AppSettingsState component name to avoid collisions

---

src/main/java/com/tabnine/inline/InlineCompletionHandler.java
src/main/java/com/tabnine/inline/TabnineDocumentListener.java
src/main/java/com/tabnine/inline/listeners/InlineCaretListener.kt
src/main/java/com/tabnine/inline/listeners/InlineKeyListener.kt

- removed the debouncer from all relevant places - the `TabnineDocumentListener` and `CompletionPreview`
- changed key listener to only clear preview on delete / backspace
- changed caret listener to only clear if the change is not a single char typing change

remove debouncer from inline

---

src/main/java/com/tabnine/inline/render/BlockElementRenderer.kt
src/main/java/com/tabnine/inline/render/GraphicsUtils.kt

When showing inline completions, replacing `\t`s with the appropriate amount of spaces.
It happens to be the case that `Graphics.drawString` counts `\t` as 0 length - you can also check that `FontMetrics.stringWidth` returns 0 for `\t`.
Before:
After:

fix snippets tabs

---

src/main/java/com/tabnine/selections/AutoImporter.java

Apparently there's another "quick fix" action - `optimize imports` - which removes the completed import.

fix auto imports bug

---

src/main/java/com/tabnine/binary/requests/autocomplete/CompletionPostprocess.kt
src/test/java/com/tabnine/plugin/completionPostProcess/Mixed.kt
src/test/java/com/tabnine/plugin/completionPostProcess/Spaces.kt
src/test/java/com/tabnine/plugin/completionPostProcess/Tabs.kt

Where the last line is empty, the trimming is done correctly:
But where you start writing a prefix which matches the snippet, the `postprocess` function is skipping the trimming part:
Calculate the indentation regardless of any subsequent text in the last line, there's no need to guard this function with the `if (lastLine.isBlank())`.

make postprocess work for non-empty lines

---

src/main/java/com/tabnine/UninstallListener.kt
src/main/java/com/tabnine/general/PluginsZipReader.kt
src/test/kotlin/integration/uninstall/UninstallListenerTest.kt

Since the latest alpha release caused FP uninstall events internally (@boaz-codota and @amircodota) - 
And since this code has been manually and automatically tested pretty thoroughly -
My current suspicion is that the "stale" check I added causes the FP.
IJ downloads the new plugin version when it decides to check for updates, which is not necessarily related to when the users wants to update.
Note that without the "stale" check, there could be TN now - users who had the new plugin version downloaded and decided to uninstall will not fire an uninstall event.

uninstall fix - stop time check on the newer version zip

---

src/main/java/com/tabnine/inline/render/DefaultTabnineInlay.kt

Got these a few times in the past couple days:
```
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
at java.base/java.util.Objects.checkIndex(Objects.java:372)
at java.base/java.util.ArrayList.get(ArrayList.java:459)
at com.tabnine.inline.render.DefaultTabnineInlay.render(DefaultTabnineInlay.kt:57)
at com.tabnine.inline.CompletionPreview.createPreview(CompletionPreview.java:105)
at com.tabnine.inline.CompletionPreview.createInstance(CompletionPreview.java:69)
at …
```

dont try to render empty string

---

src/main/java/com/tabnine/binary/requests/notifications/shown/SnippetShownRequest.kt

the context field was being sent with camelCase, while the binary expected snake_case.
this, combined with the relevant binary PR created the situation where no snippet related fields where added to the event

fix snippet shown event

---

src/main/java/com/tabnine/Initializer.java

Removing the userState initialization from the initialize() method as it may be too early in some cases, and moving it to be when it got referenced.

fix: change userState initialization time

---

src/test/java/com/tabnine/plugin/CompletionHintTests.java

problem was `isEligibleForSuggestionHint` is relying on a state which is not being cleared between tests, and should not be used in tests at all imo:
```kotlin
val isEligibleForSuggestionHint: Boolean
get() {
if (isHintShown) {
return false
}
val daysDiff = Utils.getDaysDiff(Date(), installationTime)
return daysDiff in 0..MAX_DAYS_TO_SHOW_SUGGESTION_HINT
}
// ... code
private val isHintShown: Boolean
get() = PropertiesComponent.getInstance()
.getBoolean(IS_SUGGESTION_HINT_SHOWN_STORAGE_KEY, false)
```
I fixed it by mocking this function instead of instantiating this object with the correct date.

fix mocks in completion hint tests

---

src/main/java/com/tabnine/binary/requests/selection/SelectionRequest.java
src/main/java/com/tabnine/capabilities/RenderingMode.java
src/main/java/com/tabnine/capabilities/SuggestionsMode.java
src/main/java/com/tabnine/general/DependencyContainer.java
src/main/java/com/tabnine/inline/CompletionPreview.java
src/main/java/com/tabnine/selections/CompletionPreviewListener.java
src/main/java/com/tabnine/selections/TabNineLookupListener.java

Until now it reported the rendering mode determined by the binary, but this is not what we're looking for with this report - we want to know per selection how it was **actually** rendered - so sending "hybrid" doesn't say anything.
I created another enum which represents the actual rendering that took affect, and separated it from the "suggestions mode" which the binary determines.

change rendering mode reporting

---

src/main/java/com/tabnine/inline/CompletionTracker.kt
src/main/java/com/tabnine/inline/InlineCompletionHandler.java
src/main/java/com/tabnine/userSettings/AppSettingsState.kt

- change debouncer default delay to 0. 
- disable debouncer on lookAhead flow. 
- move debouncer to be after completions have been fetched.

fix: change debouncer behaviour

---

src/main/java/com/tabnine/inline/CompletionUtils.kt

After Updating my alpha plugin from @yairco1990 's last pr (#398), my IDE started to get significantly slower, and I saw this error message occur several times:
```
2022-10-25 00:47:07,401 [ 496260] SEVERE - #c.i.o.a.i.FlushQueue - Invalid range specified: (1089, 976)
....
```
The conditions I added are matching the assertion being done at the `TextRange.java` class: 
```java
private static boolean isProperRange(int startOffset, int endOffset) {
return startOffset <= endOffset && startOffset >= 0;
}
```

fix invalid range exception

---

.github/workflows/ci.yml
src/main/java/com/tabnine/inline/CompletionPreview.java
src/main/java/com/tabnine/inline/CompletionPreviewUtils.kt
src/test/java/com/tabnine/plugin/InlineCompletionTests.java
src/test/java/com/tabnine/testUtils/TestData.java

**problem:**  
Tabnine returns the  `old_suffix`  to be replaced by the new_prefix (current suggestion)
for now, this logic is relevant only in single-line suggestions.
**example:** 
in the case of `console("H<caret>")`  and `new_prefix :ello")` Tabnine will return  `old_suffix: ")` to be replaced by the `new_prefix`
**notes:**
- this logic s not relevant to multiline suggestions because it is already handled [here](https://github.com/codota/triton-cloud-frontend/blob/a8997be6f66c7312567b819068e0f05db798afdb/app/suggestion_processing/postprocessors/overlap.py#L18)
- we have the same workaround in vscode as well https://github.com/codota/tabnine-vscode/blob/c0a9a7d5a19e4a9ef23579ce8688d216d1aab439/src/provideInlineCompletionItems.ts#L87
- this logic is calculated …

Dev2 1835 - do not modify the old suffix in case multiline suggestions

---

src/main/java/com/tabnine/binary/fetch/BootstrapperSupport.java
src/main/java/com/tabnine/binary/requests/statusBar/StatusBarInteractionRequest.java
src/main/java/com/tabnine/general/BrowserUtilsService.kt
src/main/java/com/tabnine/general/GettingStartedManager.kt
src/main/java/com/tabnine/general/ProjectUtils.kt
src/main/java/com/tabnine/lifecycle/PluginInstalledNotifier.java
src/main/java/com/tabnine/statusBar/StatusBarActions.kt
src/main/java/com/tabnine/statusBar/StatusBarPopupListener.java
src/main/java/com/tabnine/statusBar/TabnineStatusBarWidget.java
src/main/resources/META-INF/plugin.xml

- isolate the browser functionality from GettingStartedManager 
- open the getting started page on the focused project
- change the explicit reference to GettingStartedManager to event-based approach
- change user-interaction event to happen on the status bar click
- set a different event for the "open hub" popup button

DEV2-1681 - "Getting started" improvements

---

src/main/java/com/tabnine/binary/BinaryProcessRequesterProvider.java
src/main/java/com/tabnine/general/DependencyContainer.java
src/main/java/com/tabnine/inline/CompletionPreview.java
src/main/java/com/tabnine/inline/CompletionPreviewToggleEventSender.kt
src/test/java/com/tabnine/MockedBinaryCompletionTestCase.java
src/test/java/com/tabnine/integration/PredictionTimeoutIntegrationTests.java
src/test/java/com/tabnine/testUtils/BadResultsUtils.java

This PR also includes a fix to the tests from #424 - since this PR increased the TOs threshold to 80, it caused the tests to take longer and even fail sometimes.
I fixed it by passing the TOs and restarts thresoleds as data members to `BinaryProcessRequesterProvider`, and change the values for tests in `DependencyContainer.setTesting`

DEV2-1716 previous and next suggestion events

---

src/main/java/com/tabnine/general/CompletionsEventSender.kt

there's no reason to use a UI thread for this operation

DEV2-1717 use non UI thread

---

src/main/java/com/tabnine/binary/requests/notifications/shown/SuggestionShownRequest.kt
src/main/java/com/tabnine/capabilities/Capability.java
src/main/java/com/tabnine/general/Utils.java
src/main/java/com/tabnine/inline/DebounceUtils.kt
src/main/java/com/tabnine/inline/EscapeHandler.java
src/main/java/com/tabnine/inline/InlineCompletionCache.kt
src/main/java/com/tabnine/inline/InlineCompletionHandler.java
src/main/java/com/tabnine/inline/TabnineDocumentListener.java
src/main/java/com/tabnine/inline/TabnineInlineLookupListener.kt
src/main/java/com/tabnine/inline/listeners/InlineCaretListener.kt
src/main/java/com/tabnine/prediction/TabNineCompletion.java
src/test/java/com/tabnine/plugin/CompletionHintTests.java
src/test/java/com/tabnine/unitTests/InlineCompletionCacheTests.kt

Changes:
- As long as you type as the suggested completion preview, the suggestion won't be changed
- Once you type a different character than the suggested completion preview, you will get a new suggestion from the binary
- Send "SuggestionShown" event only for new and rendered completion
- Change the lousy design in `InlineCompletionHandler.java` that executes a different code for tests and different code for the actual application to be the same code
-  The previous change led to a failed test in `CompletionHintTests.java`, and apparently, I removed it by accident in a previous PR. I reverted the change. (it was an experimental feature)
- Add more debounce value capabilities
https://user-images.githubusercontent.com/10290661/206501227-a029ee5f-3028-4f35-a7bf-16f8e1e23a92.mp4

DEV2-1779: - prevent switchable suggestion. - a fix for flickering suggestions. - add debounce value capabilities.

---

src/main/java/com/tabnine/binary/BinaryProcessRequesterProvider.java
src/main/java/com/tabnine/general/DependencyContainer.java
src/main/java/com/tabnine/general/StaticConfig.java
src/test/java/com/tabnine/MockedBinaryCompletionTestCase.java
src/test/java/com/tabnine/integration/PredictionTimeoutIntegrationTests.java
src/test/java/com/tabnine/testUtils/MockAnswersUtils.kt
src/test/java/com/tabnine/testUtils/TestData.java

We were declaring the binary as "bad" based on x consecutive requests that timed out.
This approach proved to be incorrect, as since we defined this x, we added some serious polling requests - thus we began to reach this timeout threshold too quickly.
In #424, I increased this threshold from 20 to 80, just to remediate with a quick and easy solution.
This pr is the more serious solution - measure time between successful requests instead of TOs counter.
The logic goes like so:
1. on successful request - restart timeouts tracking
2. on timeout:
1. if it's the first after a successful request - set the time to now.
2. if now - `firstTimeoutMillis` > threshold -> restart
Current threshold is 1 minute (60k ms).

DEV2-1536 binary TOs - measure time instead of counter

---

src/main/java/com/tabnine/inline/CompletionUtils.kt
src/main/java/com/tabnine/inline/TabnineDocumentListener.java

this will solve the multiple events that are dispatched when typing enter after opening bracket `{`
https://user-images.githubusercontent.com/10290661/207634165-af7b9b30-3673-4d96-8c8b-ce4b0665b838.mp4
https://user-images.githubusercontent.com/10290661/207635602-25f64915-24d5-4b0d-8799-db9970995b36.mp4

DEV2-1779: trigger autocomplete on indentation

---

src/main/java/com/tabnine/general/StaticConfig.java

The theory is:
-> Multiple IDEs are running, current version = `x.x.x`
-> IDE 1 downloads a new version (= `x.x.y`) and schedules a restart to all the binaries
-> bootstrapper 2 receives the scheduled restarts and its bootstrapper kills the process -- current `.active` file is `x.x.x`
-> IDE 2 detects that the binary is dead, and spawns a new process from the `.active` file - which is still `x.x.x`
-> bootstrapper 2 detects that `x.x.y` is the desired version which is > from current (`x.x.x`) - marks the `.active` to be `x.x.y` and kills the process
-> IDE 2 detects a dead binary for the second time, and re-runs from the `.active` - which is now the updated `x.x.y`.
This means that IDE 2 restarts **twice** per version update
The restarts threshold was 5 ==> if there were 5 requests while …

DEV2-1536 increase restarts threshold

---

channels/alpha/com/tabnine/config/Config.java
channels/beta/com/tabnine/config/Config.java
channels/production/com/tabnine/config/Config.java

This is needed so we can move this service to GCP

DEV2-1967: Use CNAME for tabnine-logs

---

.github/workflows/production-new-version.yml

from the [checkout action's readme](https://github.com/actions/checkout):
> Only a single commit is fetched by default, for the ref/SHA that triggered the workflow. Set fetch-depth: 0 to fetch all history for all branches and tags.

DEV2-1921 fix checkout step

---

src/main/java/com/tabnine/inline/InlineCompletionHandler.java
src/main/java/com/tabnine/logging/TabnineLogDispatcher.kt

**Background:**
In some cases, IJ fires multiple events on a single document change. For example, after a line breakת it fires two events, where the first event is relevant for the completion but the other one is not ("\n" change event and then "empty" event with offset correction).
When we are about to render the completion, we check if it's relevant by checking that modificationStamp and offset haven't changed. 
**The problem:**
When such a scenario occurs (like that in the example), This is the order of events:
1. we get the first "\n" event 
2. we save the editor's modificationStamp and offset
3. we are invoking a non-AWT thread that should handle the completions fetching and rendering
4. we get the second "empty" event which modifies the editor's modificationStamp and offset - this …

DEV2-2041: fix impact of multiple document change event on inline completions

---

src/main/java/com/tabnine/inline/InlineCompletionHandler.java

If debounce is enabled, re-fetch completions after debounce time has passed to get better completions.
In the video, we can see that after the debounce time we get new completions that we didn't get before.
https://user-images.githubusercontent.com/10290661/209967128-80496c60-74b3-408f-af28-1f9fdd97a705.mp4

DEV2-2042: refetch suggestions after debounce

---

src/main/java/com/tabnine/binary/BinaryProcessRequesterProvider.java

Once we're working with a generic `Map<String, Object>`, Gson decides that it serializes all numbers to floats, so 1 will turn into 1.0.
Then we return this 1.0 to the binary, and the binary expects `usize` - so it fails to deserialize the context.
Example context object as being sent from the plugin:
```json
{
"snippet_id": "649abb3e-3c85-4662-93f6-354ce169e6a6",
"user_intent": "NewLine",
"intent_metadata": {
"current_line_indentation": 12.0,
"previous_line_indentation": 12.0,
"triggered_after_character": ","
},
"is_cached": true,
"generated_tokens": 20.0,
"first_token_score": "0.961",
"stop_reason": "stop_token",
"response_time_ms": 983.0,
"context_len": 346.0,
"resolved_dependencies": false,
"fetched_hinting": false
}
```
Based on this [S.O …

DEV2-1956 fix serialization

---

src/main/java/com/tabnine/binary/requests/autocomplete/AutocompleteResponse.java
src/main/java/com/tabnine/binary/requests/autocomplete/CompletionMetadata.kt
src/main/java/com/tabnine/binary/requests/autocomplete/ResultEntry.java
src/main/java/com/tabnine/binary/requests/notifications/shown/SuggestionShownRequest.kt
src/main/java/com/tabnine/general/StaticConfig.java
src/main/java/com/tabnine/inline/InlineCompletionHandler.java
src/main/java/com/tabnine/inline/render/DefaultTabnineInlay.kt
src/main/java/com/tabnine/intellij/completions/CompletionUtils.java
src/main/java/com/tabnine/intellij/completions/TabNineCompletionContributor.java
src/main/java/com/tabnine/prediction/TabNineCompletion.java
src/main/java/com/tabnine/selections/CompletionPreviewListener.java
src/main/java/com/tabnine/selections/SelectionUtil.java
src/main/java/com/tabnine/selections/TabNineLookupListener.java
src/test/java/com/tabnine/testUtils/TestData.java
src/test/java/com/tabnine/unitTests/InlineCompletionCacheTests.kt

In order to support suggestion-dropped events we first need to use the new API version 4.4.223.
This pr only handles the migration to this API version, I will add the new event in a separate pr.
1. Introduce `CompletionMetadata` class - its fields were flattened inside `ResultEntry` (and `snippet_context` in `AutocompleteResult`)
Now, `ResultEntry` has a `completion_metadata` field with all these un-flattened fields.
2. Change `SuggestionShown` event args - it now accepts this `CompletionMetadata` object instead of "kind" and "origin".
The rest of the changes are all direct consequences of these 2 changes.

DEV2-2022 use new api version 4.4.223

---

src/main/java/com/tabnine/Initializer.java
src/main/java/com/tabnine/general/SubscriptionType.kt
src/main/java/com/tabnine/lifecycle/BinaryStateService.java
src/main/java/com/tabnine/notifications/ConnectionLostNotificationHandler.kt
src/main/java/com/tabnine/statusBar/TabnineEnterpriseStatusBarWidget.java

previously, the update loop was initialized in the constructor of `BinaryStateServiec`.
the issue is that in onprem, we never called this service, so the constructor was never called.
i changed it so that the loop init is explicit and will be called within the `Initialize` extension point.

DEV2-2435 add health check

---

src/main/java/com/tabnine/general/CompletionsEventSender.kt
src/main/java/com/tabnine/inline/ManualTriggerTabnineInlineCompletionAction.kt
src/main/java/com/tabnine/intellij/completions/TabNineCompletionContributor.java
src/main/resources/META-INF/plugin.xml
src/test/java/com/tabnine/integration/PredictionBehaviourIntegrationTests.java
src/test/java/com/tabnine/plugin/InlineCompletionTests.java

users should define the shortcut for this action manually - no default shortcut is provided.

DEV2-2518 add manual trigger inline completion action

---

build.gradle
src/main/java/com/tabnine/general/StaticConfig.java

re-opening #494, since i found a small mistake in my changes and the diff got messed up anyway.
tests:
I installed locally on ij 2019 from a locally-built plugin, status bar and completions seem to work as expected.

DEV2-2537 upgrade to language level 9

---

src/main/java/com/tabnine/binary/BinaryProcessGateway.kt
src/main/java/com/tabnine/userSettings/AppSettingsComponent.kt
src/main/java/com/tabnine/userSettings/AppSettingsConfigurable.kt
src/main/java/com/tabnine/userSettings/AppSettingsState.kt

By default, we are getting the proxy settings from IntelliJ and inheriting them to the binary.
This won't happen if the checkbox is disabled.
Was able to see the binary requests via `mitmproxy` when the setting was on.
Process env var in windows:
windows proxy:

DEV2-2535: Use IntelliJ Proxy settings

---

.github/workflows/production-new-version.yml

Need first to set the version, then to publish. Missed that.

DEV2-2535: Fix missing need for step

---

Common/build.gradle
Tabnine/build.gradle
TabnineSelfHosted/build.gradle
TabnineSelfHostedForMarketplace/build.gradle

now it will always produce the same plugin name even if the project name is different

DEV2-2560: Fix publish with wrong name

---

Common/src/main/java/com/tabnineCommon/inline/CompletionTracker.kt
Common/src/main/java/com/tabnineCommon/inline/InlineCompletionHandler.java

using the existing debounce mechanism which fetches before debouncing and then re-fetches after, just applying the same logic with debounce time = 800ms when results are empty. 
you can see in the attached video that I did not type as suggested multiple times, and received completions each time.
https://github.com/codota/tabnine-intellij/assets/67855609/a539f6cb-1a06-4839-98b0-1b7244361cf0

DEV2-2856 re-fetch suggestions when results are empty

---

Common/src/main/java/com/tabnineCommon/binary/fetch/BinaryVersionFetcher.java
Common/src/main/java/com/tabnineCommon/binary/fetch/BootstrapperSupport.java

they have an isue updating in envs with custom certificates, so it is up to the plugin to download a newer version with a fix

DEV2-3062 Do not run binary versions 4.5.0 through 4.5.13

---

Common/src/main/java/com/tabnineCommon/chat/ChatBrowser.kt
Common/src/main/java/com/tabnineCommon/chat/actions/TabnineActionsGroup.kt
Common/src/main/java/com/tabnineCommon/chat/actions/toolWindowActions/OpenDevToolsAction.kt

Since we need it to debug user complaints, and its already enabled by default in vscode, there's no harm in allowing this in jb as well.
https://github.com/codota/tabnine-intellij/assets/67855609/3e0d64a3-5b7d-4d01-8b7a-1fd783bc7052

DEV2-2972 add open devtools action

---

Tabnine/src/main/java/com/tabnine/statusBar/StatusBarPromotionProvider.java
Tabnine/src/main/java/com/tabnine/statusBar/StatusBarProvider.java
Tabnine/src/main/java/com/tabnine/statusBar/TabnineStatusBarWidget.java
Tabnine/src/main/resources/META-INF/plugin.xml
TabnineSelfHosted/src/main/java/com/tabnineSelfHosted/statusBar/StatusBarProvider.kt
TabnineSelfHosted/src/main/java/com/tabnineSelfHosted/statusBar/TabnineSelfHostedStatusBarWidget.kt
TabnineSelfHosted/src/main/resources/META-INF/plugin.xml
TabnineSelfHostedForMarketplace/src/main/java/com/tabnineSelfHosted/statusBar/StatusBarForMarketPlaceProvider.kt
TabnineSelfHostedForMarketplace/src/main/java/com/tabnineSelfHosted/statusBar/TabnineSelfHostedForMarketPlaceStatusBarWidget.kt
TabnineSelfHostedForMarketplace/src/main/resources/META-INF/plugin.xml

following this [suggested workaround](https://youtrack.jetbrains.com/issue/IDEA-319569/Status-bar-provided-by-StatusBarProvider-disappears-sometimes-when-the-new-UI-is-enabled-Tabnine#focus=Comments-27-7545061.0-0) by the JB team
It appears to be the case that after you hide the status bar manually, you can't make it re-appear - and it looks like its a bug on JB's side, I've already informed them and waiting for their response [on this issue](https://youtrack.jetbrains.com/issue/IDEA-319569/Status-bar-provided-by-StatusBarProvider-disappears-sometimes-when-the-new-UI-is-enabled-Tabnine#focus=Comments-27-7861481.0-0).
Other than that, looks like it works OK.
I have tested the 3 plugins (production, self hosted, and marketplace) - both with the `runIde` job (i.e on IJ 2020.2), and by …

DEV2-2661 fix missing status bar

---

Common/src/main/java/com/tabnineCommon/chat/ChatMessagesRouter.kt
Common/src/main/java/com/tabnineCommon/chat/commandHandlers/chatState/ChatState.kt
Tabnine/src/test/java/com/tabnine/unitTests/GsonSerDeTests.kt

since the latest fixes to the intent detection mechanism, the UI relies on the `intent` field of the conversation state to render the chat history (combines the intent to the user's question to create the entire title of the chat item)
for example, here it joins "/explain-code" to "with text" for the title: 
since kotlin&java are strict with serialization, we need to add this field explicitly in order for it to be persisted

DEV2-3336 add intent to conversation state

---

Common/src/main/resources/META-INF/common-plugin.xml
Tabnine/src/main/resources/META-INF/plugin.xml

they require a max of 64 chars in the latest EAP, and ours is 66 🤦🏻 - so I removed "php" from the name
the job is passing on this branch: https://github.com/codota/tabnine-intellij/actions/runs/5916121678/job/16043040814

DEV2-3485 shorten plugin name to pass compatibility check with latest EAP 

---

Common/src/main/java/com/tabnineCommon/general/Utils.java
TabnineSelfHostedForMarketplace/build.gradle
TabnineSelfHostedForMarketplace/src/main/java/com/tabnineSelfHosted/SelfHostedInitializer.kt
TabnineSelfHostedForMarketplace/src/main/java/com/tabnineSelfHosted/Utils.kt
TabnineSelfHostedForMarketplace/src/main/java/com/tabnineSelfHosted/userSettings/AppSettingsState.kt

There were serval bugs:
1. The updater didn't set the URL after the user set it.
2. Which made it not to add the custom repository
3. It was permanently replacing the same value
I think this needs to be published to the marketplace and fix the version in the 1.2.0 branch, is the code also called from there

DEV2-3719: Fix URL when downloading self hosted version

---

Common/src/main/java/com/tabnineCommon/userSettings/AppSettingsState.kt
TabnineSelfHosted/src/main/java/com/tabnineSelfHosted/Initializer.kt
TabnineSelfHostedForMarketplace/src/main/java/com/tabnineSelfHosted/SelfHostedInitializer.kt

The problem is that the `AppSettingsState` is different type than the one in for the marketplace, so for that to work it have to come as a callback. also applied the fixes to the save function

DEV2-3719: Apply the fix also for regular self hosted

---

Common/src/main/java/com/tabnineCommon/chat/ChatBrowser.kt
Common/src/main/java/com/tabnineCommon/chat/ChatFrame.kt
Common/src/main/java/com/tabnineCommon/chat/ChatMessagesRouter.kt
Common/src/main/java/com/tabnineCommon/chat/TabnineChatWebViewFactory.kt
Common/src/main/java/com/tabnineCommon/chat/actions/common/ChatActionCommunicator.kt

An action can't invoke the chat tool window before the user manually opens it in the current session.
It happens because `ChatBrowser.getInstance` would return `null` until the user opens the tool window, thus creating a browser instance.
I solved it by making the browser creation available from anywhere, not just from the user's manual hook.
This solution required the following:
1. Making the `ChatMessagesRouter` singleton and not pass it in the creation phase.
2. Changing `ChatBrowser.getInstance` to create an instance if it doesn't exist on the project's user data, and making the constructor private to prevent double-creation per project.
3. Changing the "browser loaded" listeners to "chat app startup" listeners
This was necessary because the previous implementation simply didn't work: …

DEV2-3931 fix chat first loading

---

Common/src/main/java/com/tabnineCommon/chat/ChatBrowser.kt
Common/src/main/java/com/tabnineCommon/chat/ChatFrame.kt
Common/src/main/java/com/tabnineCommon/chat/ChatMessagesRouter.kt
Common/src/main/java/com/tabnineCommon/chat/TabnineChatWebViewFactory.kt
Common/src/main/java/com/tabnineCommon/chat/actions/AskChatAction.kt
Common/src/main/java/com/tabnineCommon/chat/actions/TabnineQuickFixAction.kt
Common/src/main/java/com/tabnineCommon/chat/actions/common/ChatActionCommunicator.kt
Common/src/main/resources/META-INF/common-plugin.xml
Common/src/main/resources/intentionDescriptions/TabnineQuickFixAction/description.html

Add a "Fix using Tabnine" quick-action
1. This action opens the chat window and sends it the text `"/fix-code"`.
2. This action only appears if there's at least one warning/error level diagnostic in the selected code range, or - if no code is selected - on the PSI element the cursor is on.

DEV2-3931 add quick fix action

---

Tabnine/src/main/resources/META-INF/plugin.xml
TabnineSelfHosted/src/main/resources/META-INF/plugin.xml
TabnineSelfHostedForMarketplace/src/main/resources/META-INF/plugin.xml

from the alpha release CI job [logs](https://github.com/codota/tabnine-intellij/actions/runs/6469012328/job/17562221422):
```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':Tabnine:publishPlugin'.
> Failed to upload plugin: Upload failed: Extension Point in the &lt;com.intellij.statusBarWidgetFactory&gt; element must have 'id' attribute set with same value returned from the getId() method of the com.tabnine.statusBar.StatusBarProvider implementation.
Extension Point in the &lt;com.intellij.statusBarWidgetFactory&gt; element must have 'id' attribute set with same value returned from the getId() method of the com.tabnine.statusBar.StatusBarPromotionProvider implementation.
> Task :Tabnine:publishPlugin FAILED
```

DEV2-3931 fix alpha release job

---

Common/src/main/java/com/tabnineCommon/chat/commandHandlers/ChatMessageHandler.kt

error logs are being presented to the user in this stressful message window
but it isn't really a non-recoverable error, so no need to stress the user so much.
especially when it happens when you close a project.

DEV2-4218 don't log "failed to get editor" as error

---

Common/src/main/java/com/tabnineCommon/chat/commandHandlers/WorkspaceFoldersHandler.kt
Common/src/main/java/com/tabnineCommon/lifecycle/WorkspaceListenerService.kt

- when updating the binary: iterate over all opened projects, and update all the root paths within them
- when answering the chat's `workspace_folders` request - only reply with the root paths in the chat's respective project
I ran 2 IJ windows, each one with 2 projects in their workspace, and made sure that each indexing indication reflected the correct status according to the project, and that the binary request contains the paths from both windows together

DEV2-4253 refine workspace folders resolution
