codota/tabnine-intellij

src/main/java/com/tabnine/TabNineCompletionContributor.java
=> concatenate user messages util the max valid length

build.gradle, src/main/java/com/tabnine/DependencyContainer.java, src/main/java/com/tabnine/StaticConfig.java, src/main/java/com/tabnine/TabNineInitializer.java, src/main/java/com/tabnine/TabNinePluginStateListener.java, src/main/java/com/tabnine/Utils.java, src/main/java/com/tabnine/binary/BinaryRun.java, src/main/java/com/tabnine/exceptions/TabNineDeadException.java, src/main/resources/META-INF/plugin.xml, src/test/java/com/tabnine/binary/BinaryRunTests.java
No integration tests possible due to IntelliJ Plugin SDK not enabling it.
Co-Authored-By: Eransho <24720660+Eransho@users.noreply.github.com>
=> Uninstall hook

src/main/java/com/tabnine/binary/requests/notifications/NotificationOptions.kt, src/main/java/com/tabnine/binary/requests/notifications/actions/HoverActionRequest.kt, src/main/java/com/tabnine/binary/requests/notifications/actions/NotificationActionRequest.kt, src/main/java/com/tabnine/binary/requests/statusBar/StatusBarPromotionActionRequest.kt, src/main/java/com/tabnine/binary/requests/statusBar/StatusBarPromotionBinaryResponse.kt, src/main/java/com/tabnine/general/NotificationOption.kt, src/main/java/com/tabnine/lifecycle/BinaryNotificationsLifecycle.kt, src/main/java/com/tabnine/statusBar/StatusBarPromotionWidget.java
fix broken openhub action + actions type as any
=> fix broken openhub action + actions type as any

src/main/java/com/tabnine/selections/AutoImporter.java
Calling the code analyzer auto import inside a write lock
=> Running the analyzing later in write lock

src/main/java/com/tabnine/binary/requests/autocomplete/ResultEntry.java, src/main/java/com/tabnine/binary/requests/selection/SelectionRequest.java, src/main/java/com/tabnine/binary/requests/selection/SetStateBinaryRequest.java, src/main/java/com/tabnine/general/CompletionKind.java, src/main/java/com/tabnine/general/StaticConfig.java, src/main/java/com/tabnine/intellij/completions/TabNineCompletionContributor.java, src/main/java/com/tabnine/prediction/TabNineCompletion.java, src/main/java/com/tabnine/selections/TabNineLookupListener.java
=> upgrade api version to 3.5.34

src/main/java/com/tabnine/inline/TabnineDocumentListener.java
- JB throws exception 
- such use case should be ignored anyway (no sure what its frequency, looks rare)
=> Don't continue with method logic if we are not in EDT thread

src/main/java/com/tabnine/binary/requests/autocomplete/AutocompleteRequest.java, src/main/java/com/tabnine/prediction/CompletionFacade.java, src/test/java/com/tabnine/testutils/TestData.java
=> Add offset, line & character

src/main/java/com/tabnine/userSettings/AppSettingsComponent.kt
=> add "requires restart" to log file path property

local-repo/README.md, local-repo/run-local-repo.sh
For context, read the `README.md` from this pr: https://github.com/codota/tabnine-intellij/blob/37db20fe8f8f242709ebec21be4885e504549c45/local-repo/README.md
=> add local plugin repo utility

src/main/java/com/tabnine/binary/requests/autocomplete/AutocompleteResponse.java, src/main/java/com/tabnine/binary/requests/autocomplete/UserIntent.kt, src/main/java/com/tabnine/binary/requests/notifications/shown/SnippetShownRequest.kt, src/main/java/com/tabnine/binary/requests/selection/SelectionRequest.java, src/main/java/com/tabnine/general/StaticConfig.java, src/main/java/com/tabnine/inline/InlineCompletionHandler.java, src/main/java/com/tabnine/intellij/completions/CompletionUtils.java, src/main/java/com/tabnine/intellij/completions/TabNineCompletionContributor.java, src/main/java/com/tabnine/prediction/CompletionFacade.java, src/main/java/com/tabnine/prediction/TabNineCompletion.java, src/main/java/com/tabnine/selections/CompletionPreviewListener.java, src/main/java/com/tabnine/selections/TabNineLookupListener.java
- add filename and intent to `SnippetShown`
- add intent to `AutocompleteResult` and to `SelectionRequest`
=> use api version 4.1.21

src/main/java/com/tabnine/inline/InlineCompletionHandler.java, src/main/java/com/tabnine/inline/TabnineDocumentListener.java, src/main/java/com/tabnine/inline/listeners/InlineCaretListener.kt, src/main/java/com/tabnine/inline/listeners/InlineKeyListener.kt
0 files changed between the tag before the previous pr and now
=> revert remove debouncer

src/main/java/com/tabnine/binary/BinaryRun.java, src/main/java/com/tabnine/general/StaticConfig.java, src/main/java/com/tabnine/userSettings/AppSettingsComponent.kt, src/main/java/com/tabnine/userSettings/AppSettingsConfigurable.kt, src/main/java/com/tabnine/userSettings/AppSettingsState.kt
=> add log level settings property

src/main/java/com/tabnine/binary/requests/autocomplete/CompletionPostprocess.kt, src/main/java/com/tabnine/inline/InlineCompletionHandler.java, src/main/java/com/tabnine/inline/render/GraphicsUtils.kt, src/main/java/com/tabnine/intellij/completions/CompletionUtils.java, src/main/java/com/tabnine/prediction/CompletionFacade.java, src/test/java/com/tabnine/plugin/completionPostProcess/Mixed.kt, src/test/java/com/tabnine/plugin/completionPostProcess/Spaces.kt, src/test/java/com/tabnine/plugin/completionPostProcess/Tabs.kt, src/test/java/com/tabnine/plugin/completionPostProcess/driver.kt
See the description on pr 1805 in our binary project for more details.
=> trim snippets with respect to indentation

src/main/java/com/tabnine/inline/render/GraphicsUtils.kt
pr https://github.com/codota/tabnine-intellij/pull/313 indeed swallowed the exception, but always returned null
=> really fix tabSize exception

src/main/java/com/tabnine/capabilities/CapabilitiesService.java
in order to catch binary config changes in somewhat "real time", we shorten the interval between capabilities refresh
=> refresh capabilities more often

.gitignore, src/main/java/com/tabnine/binary/requests/autocomplete/AutocompleteResponse.java, src/main/java/com/tabnine/binary/requests/autocomplete/SnippetContext.kt, src/main/java/com/tabnine/binary/requests/notifications/shown/SnippetShownRequest.kt, src/main/java/com/tabnine/binary/requests/selection/SelectionRequest.java, src/main/java/com/tabnine/general/StaticConfig.java, src/main/java/com/tabnine/inline/InlineCompletionHandler.java, src/main/java/com/tabnine/intellij/completions/CompletionUtils.java, src/main/java/com/tabnine/prediction/TabNineCompletion.java, src/main/java/com/tabnine/selections/CompletionPreviewListener.java, src/main/java/com/tabnine/selections/TabNineLookupListener.java
bump api version - snippet context added
ref: https://github.com/codota/acpl-paid/pull/2071
=> bump api version - snippet context added

src/main/java/com/tabnine/inline/AcceptTabnineInlineCompletionAction.kt, src/main/java/com/tabnine/inline/InlineKeybindingHintUtil.java, src/main/java/com/tabnine/inline/ShowNextTabnineInlineCompletionAction.kt, src/main/java/com/tabnine/inline/ShowPreviousTabnineInlineCompletionAction.kt, src/main/resources/META-INF/plugin.xml, src/test/java/com/tabnine/plugin/InlineCompletionTests.java
=> fix conflicting action ids with other plugins

src/main/java/com/tabnine/inline/CompletionUtils.kt, src/main/java/com/tabnine/inline/TabnineDocumentListener.java, src/test/java/com/tabnine/plugin/InlineCompletionTests.java
Copy of the same behaviour from vscode
https://github.com/codota/tabnine-vscode/pull/956
**before**:
https://user-images.githubusercontent.com/10290661/197491449-2db715aa-5958-42ba-becf-756bbcb20ea0.mp4
https://user-images.githubusercontent.com/10290661/197491456-fbf35226-231a-49f1-aad9-3ea1d69261e9.mp4
**after**:
https://user-images.githubusercontent.com/10290661/197491512-1b9ded67-9a19-4e33-80c7-38fa8f49fa59.mp4
https://user-images.githubusercontent.com/10290661/197491502-24e8c81a-c73e-4663-9856-8044b1b5ab7b.mp4
=> disable suggestions on paste (length > 1) or tab(indent in)

.github/workflows/ci.yml, build.gradle
from [snyk's docs](https://docs.snyk.io/products/snyk-open-source/language-and-package-manager-support/snyk-for-java-gradle-maven#configurations):
> "By default Snyk merges all configurations returned by Gradle to dependency graph based on the sum total of the dependencies across all configurations in the project/projects."
=> fix snyk job

src/main/java/com/tabnine/general/StaticConfig.java, src/main/java/com/tabnine/lifecycle/BinaryNotificationsLifecycle.kt
- support multiple notification buttons
- change notification icon
**QA:**
verifying we get multiple buttons
=> DEV2-1719 - support multiple notification buttons

src/main/java/com/tabnine/statusBar/TabnineStatusBarWidget.java
https://tabnine.atlassian.net/browse/DEV2-1858
=> DEV2-1858: validate myStatusBar is not null while updating it

src/main/java/com/tabnine/general/StaticConfig.java, src/main/java/com/tabnine/userSettings/AppSettingsComponent.kt, src/main/java/com/tabnine/userSettings/AppSettingsConfigurable.kt, src/main/java/com/tabnine/userSettings/AppSettingsState.kt
⚠️ Note - there's no input validation atm, so the path change can lead to unexpected behavior
=> DEV2-1865 add binaries location settings option

src/main/java/com/tabnine/inline/InlineCompletionHandler.java
when debounce is enabled, the completion preview creation is delayed, and therefore the registration to the caret listener is also delayed as it's attached to the preview.
I added a check that allows rendering completions just in case the offset on the document change and the offset on the rendering moment are equal, otherwise, cancel the rendering.
before fix:
https://user-images.githubusercontent.com/10290661/209736592-464ee789-6eaa-431c-a8b1-8215fef01d1e.mp4
after fix:
https://user-images.githubusercontent.com/10290661/209736609-026d7345-7b9f-4dc3-b8e3-fd17527b23e5.mp4
=> DEV2-1779: fix late registration to caret listener when debounce is enabled

.github/workflows/production-new-version.yml
The `checkout` isn't taking the code after setting the version, so we need to take it explicit
=> DEV2-2535: Publish the wrong version

.github/workflows/production-new-version.yml
I accidtialy change the output name :(
=> DEV2-2535: Failed artifacts publishing

.github/workflows/production-new-version.yml
it was uploading to `gs://tabnine-self-hosted-artifacts/jetbrains/TabNine-1.0.4.zip/TabNine-1.0.4.zip` 🤦🏻‍♂️
=> DEV2-2536: Fix upload path

Common/src/main/java/com/tabnineCommon/general/SubscriptionType.kt, TabnineSelfHosted/src/main/java/com/tabnineSelfHosted/statusBar/TabnineSelfHostedStatusBarWidget.kt, TabnineSelfHosted/src/main/java/com/tabnineSelfHosted/statusBar/UserLoginStatus.kt
There is a race, and the value might not be init before we ask for it.
=> DEV2-2807: Fix null pointer exception

Common/src/main/java/com/tabnineCommon/binary/BinaryRequest.java, Common/src/main/java/com/tabnineCommon/binary/BinaryRequestFacade.java, Common/src/main/java/com/tabnineCommon/binary/requests/login/LoginRequest.kt, Common/src/main/java/com/tabnineCommon/general/StaticConfig.java, TabnineSelfHosted/src/main/java/com/tabnineSelfHosted/LoginLogoutAction.kt, TabnineSelfHosted/src/main/java/com/tabnineSelfHosted/binary/lifecycle/UserInfoService.kt, TabnineSelfHosted/src/main/java/com/tabnineSelfHosted/loginNotifier.kt, TabnineSelfHosted/src/main/java/com/tabnineSelfHosted/statusBar/SelfHostedStatusBarActions.kt, TabnineSelfHosted/src/main/java/com/tabnineSelfHosted/statusBar/TabnineSelfHostedStatusBarWidget.kt
=> DEV2-2806: Show success message on login

TabnineSelfHosted/src/main/resources/META-INF/plugin.xml, TabnineSelfHostedForMarketplace/build.gradle, TabnineSelfHostedForMarketplace/src/main/resources/META-INF/plugin.xml
=> DEV2-2944: Reaname Tabnine enterprise plugin name in the marketplace

Tabnine/src/main/java/com/tabnine/BrowserCreator.kt, Tabnine/src/main/java/com/tabnine/chat/TabnineChatProjectManagerListener.kt, Tabnine/src/main/java/com/tabnine/chat/TabnineChatWebViewFactory.kt
i moved the browser creation to earlier in the flow, before registering the tool window - in order to catch its creation failure beforehand
=> DEV2-2972 catch browser creation error gracefully

Common/src/main/java/com/tabnineCommon/lifecycle/BinaryStateService.java, Tabnine/src/main/java/com/tabnine/chat/actions/ReloadAction.kt, Tabnine/src/main/java/com/tabnine/chat/actions/TabnineActionsGroup.kt, Tabnine/src/main/java/com/tabnine/chat/actions/TabnineChatAction.kt, Tabnine/src/main/java/com/tabnine/chat/commandHandlers/GetUserHandler.kt
We get alpha users complaining from time to time that the UI doesn't render inside the browser, so I added this action in hopes that it'll be able to remediate the issue when it appears.
=> DEV2-2972 add reload browser option

Tabnine/src/main/java/com/tabnine/chat/commandHandlers/GetEditorContextHandler.kt
=> DEV2-2989 support getting metadata for first file in project

.github/workflows/production-new-version.yml
=> disable production release

.github/workflows/production-new-version.yml
DEV2-3459 revert production release action
=> DEV2-3459 revert production release action

.github/workflows/codeql-analysis.yml, Common/src/main/java/com/tabnineCommon/chat/ChatDisabledComponents.kt
- bump codeql actions to v2
- add `-Xmx4g` (set maximum heap size to 4 GB)
=> DEV2-3501 fix analyze job

.github/workflows/production-new-version.yml
DEV2-3651 bump minor on release
=> DEV2-3651 bump minor on release

Common/src/main/java/com/tabnineCommon/chat/commandHandlers/InsertAtCursorHandler.kt
=> DEV2-3645 remove comment

.github/workflows/production-new-version.yml, TabnineSelfHosted/src/main/java/com/tabnineSelfHosted/loginNotifier.kt
=> DEV2-3650 - on master

Common/src/main/java/com/tabnineCommon/chat/ChatMessagesRouter.kt, Common/src/main/java/com/tabnineCommon/chat/commandHandlers/GetServerUrlHandler.kt, Common/src/main/java/com/tabnineCommon/chat/commandHandlers/InitHandler.kt, Common/src/main/java/com/tabnineCommon/chat/commandHandlers/utils/ServerUrl.kt
For now, it will return https://api.tabnine.com as default. In the future, it will ask the binary for that.
=> DEV2-3857: Add command to get the server URL

Common/src/main/java/com/tabnineCommon/chat/ChatMessagesRouter.kt, Common/src/main/java/com/tabnineCommon/chat/commandHandlers/NavigateToLocationHandler.kt
https://github.com/codota/tabnine-intellij/assets/67855609/6e0b1677-5acf-444a-bf51-f416ba699225
=> DEV2-4120 add "navigate_to_location" handler

Common/src/main/java/com/tabnineCommon/capabilities/Capability.java, Common/src/main/java/com/tabnineCommon/chat/ChatDisabledComponents.kt, Common/src/main/java/com/tabnineCommon/chat/ChatDisabledReason.kt, Tabnine/src/main/java/com/tabnine/chat/ChatEnabledState.kt
=> DEV2-4419: enable chat for preview users
